name: Release new version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to be used for the new release'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Embed version in Dockerfile
      run: sed -i "s/version=dev/version=${{ github.event.inputs.version }}/" Dockerfile; cat Dockerfile
    - name: Create release commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Version ${{ github.event.inputs.version }}"
        branch: release
        tagging_message: ${{ github.event.inputs.version}}
        push_options: '--force'
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_name: Release ${{ github.event.inputs.version }}
        tag_name: ${{ github.event.inputs.version }}
